name: 'Github action for nf-core CI'
description: 'Install nf-core CI tools and performs linting'
author: 'Maxime Borry'
branding:
  icon: 'tool'  
  color: 'green'
inputs:
  nextflow_version:
    description: 'Nextflow version'
    default: ''
  nfcore_version:
    description: 'nf-core tools version'
    default: ''
  mode:
    description: 'nf-core linting mode'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'