name: 'Github action for nf-core CI'
description: 'Install nf-core CI tools and performs linting'
author: 'Maxime Borry'
branding:
  icon: 'tool'  
  color: 'green'
inputs:
  nextflow_version:
    description: 'Nextflow version'
    default: ''
  nfcore_version:
    description: 'nf-core tools version'
    default: ''
  mode:
    description: 'nf-core linting mode'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_PR_COMMIT: ${{ github.event.pull_request.head.sha }}