name: 'Github action for nf-core CI'
description: 'Install nf-core CI tools and performs linting'
author: 'Maxime Borry'
branding:
  icon: 'tool'  
  color: 'green'
inputs:
  nextflow_version:
    description: 'Nextflow version'
    required: false
    default: ''
  nfcore_version:
    description: 'nf-core tools version'
    required: false
    default: ''
  mode:
    description: 'nf-core linting mode'
    required: false
    default: ''
  gh_comments_url: 
    description: 'PR comments URL'
    required: false
    default: ${{ github.event.pull_request.comments_url }}
  gh_token: 
    description: 'Github Token'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  gh_pr_commit: 
    description: 'Github pull request SHA'
    required: false
    default: ${{ github.event.pull_request.head.sha }}
runs:
  using: 'docker'
  image: 'Dockerfile'